apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURpVENDQW5HZ0F3SUJBZ0lSQVBkK1QwMEhtV2RuK0N1UDM0UWhXQnd3RFFZSktvWklodmNOQVFFTEJRQXcKWGpFUE1BMEdBMVVFQXd3R1N6aHpJRU5CTVFzd0NRWURWUVFHRXdKVlV6RVBNQTBHQTFVRUJ3d0dRWFZ6ZEdsdQpNUTh3RFFZRFZRUUtEQVpQY21GamJHVXhEREFLQmdOVkJBc01BMDlqYVRFT01Bd0dBMVVFQ0F3RlZHVjRZWE13CkhoY05NalV4TVRBMk1UVTFNREE0V2hjTk16QXhNVEEyTVRVMU1EQTRXakJlTVE4d0RRWURWUVFEREFaTE9ITWcKUTBFeEN6QUpCZ05WQkFZVEFsVlRNUTh3RFFZRFZRUUhEQVpCZFhOMGFXNHhEekFOQmdOVkJBb01Cazl5WVdOcwpaVEVNTUFvR0ExVUVDd3dEVDJOcE1RNHdEQVlEVlFRSURBVlVaWGhoY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCCkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUo4aDBEaWhTTmRzWHZWZnpYM1VZSWlqSlBKT2pGbDVEVTRUNVFWckp5NE4KUityKzZBSzRFZTV5LzFGZEt2a2ZKTDU1MExkQ1dqRk9ocW1TMGkxNTFRRTNlTEI3emxmVWttZE5ub04rbTlVTgpNOUY0ZGc0ZGNCWWxlaDNuN2pOWFdGM2l2WnVqUHZweGdJZ2pNSjJlUHo0NWlXVVZBOGhJTXJBQVM3N3RxR3JDCjhuYTluby80a2FsZnhvbktkMytQNlBoSERQNlZUVWRCT1pRenZIcjdWdk9WanFlaDgwdjBTdVNaNTNSZno2ckEKYkc3MnRRdjBFOTVQeUphaXZiRURBWWdveDliVDgzMkhEVHJ0UWgwaGljdkh1cm1ibHc5Z2dsUm0vWWl3NDUxRgppM0hvak5PK0NGS1I2UVMxUlJxMzdNYzA5Z3V0d0JXTVZFRTVOZ0htRmcwQ0F3RUFBYU5DTUVBd0R3WURWUjBUCkFRSC9CQVV3QXdFQi96QU9CZ05WSFE4QkFmOEVCQU1DQVFZd0hRWURWUjBPQkJZRUZKd2h5R0RHcnhqNmVFY0IKUDhhRTA0dGV2M0ZOTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCVDA5V3JYMFBYb1BKQ2hxRjNuN21xMlZaSQp5S1pTK2hvUFdyaE5LcDh4Q1dqVFFrQklxNndEcDNmV3BlVEltZFNXQ1doY1NZb0R6ZWFQS0dIT3pkQzNBQkpWCkk5cGlKYWpRaVZpeEpuR25Ubzc5U2IzU00rYlRGUXRSNGVKN3NFd1MyMGg1ZXhkcXpNRFBTNzlGU0xQS2pIay8Ka1I1QldwcHN2NS9ZWThuQ0ZZVXhWN0sxcjRUMm92ZVlSM0FRaDNVbUpNN0UzcWJ3YnNMc01YdFBHbWVOWXhaMQpjOVVDd1RscjNnK3huUjhFYWY5ZGVoeEphNkJId3hOK3l3bVcyeHRyRTNadk5PTUorUEJhcmd4c1g1Ujh5WUN1CkZPT2g3TkFvcHFHTlBZcC8yN2ZtYXlJQjVGSWNEWHpGVXdFS1hoVkJDNWtuY1pKK3FlTWw2V0xSY3ByWgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://79.72.52.242:6443
  name: cluster-colo5ddxzca
contexts:
- context:
    cluster: cluster-colo5ddxzca
    user: user-colo5ddxzca
  name: context-colo5ddxzca
current-context: context-colo5ddxzca
kind: ''
users:
- name: user-colo5ddxzca
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - ce
      - cluster
      - generate-token
      - --cluster-id
      - ocid1.cluster.oc1.eu-madrid-1.aaaaaaaagutxsbuenvhhkck3zcyv7ovfktkrrjihaauhfkwpmcolo5ddxzca
      - --region
      - eu-madrid-1
      command: oci
      env: []

