apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - flux.yaml
  - secret.yaml
  - receiver.yaml
  - provider.yaml
  - alert.yaml
  - podmonitor.yaml
  - httproute.yaml
