apiVersion: v1
kind: ConfigMap
metadata:
  name: evolution-api-config
  namespace: evolution-api
data:
  # https://github.com/EvolutionAPI/evolution-api/blob/2.3.6/.env.example
  DATABASE_ENABLED: "true"
  DATABASE_PROVIDER: "postgresql"
  DATABASE_CONNECTION_CLIENT_NAME: "evolution-api"
  LOG_LEVEL: "WEBSOCKET"
  LANGUAGE: "en"
  # Websocket - Environment variables
  WEBSOCKET_ENABLED: "true"
  WEBSOCKET_GLOBAL_EVENTS: "true"
  WEBSOCKET_ALLOWED_HOSTS: "*"
  TZ: "Europe/Madrid"
  RABBITMQ_ENABLED: "false"
  LOG_BAILEYS: "debug"

  SERVER_NAME: "evolution"
  SERVER_TYPE: "http"
  SERVER_PORT: "8080"
  # Server URL - Set your application url
  SERVER_URL: "http://localhost:8080"

  
  

  SENTRY_DSN: ""
  CORS_ORIGIN: "*"
  CORS_METHODS: "GET,POST,PUT,DELETE"
  CORS_CREDENTIALS: "true"
  LOG_COLOR: "true"
  DEL_INSTANCE: "false"
  DATABASE_SAVE_DATA_INSTANCE: "true"
  DATABASE_SAVE_DATA_NEW_MESSAGE: "true"
  DATABASE_SAVE_MESSAGE_UPDATE: "true"
  DATABASE_SAVE_DATA_CONTACTS: "true"
  DATABASE_SAVE_DATA_CHATS: "true"
  DATABASE_SAVE_DATA_LABELS: "true"
  DATABASE_SAVE_DATA_HISTORIC: "true"
  DATABASE_SAVE_IS_ON_WHATSAPP: "true"
  DATABASE_SAVE_IS_ON_WHATSAPP_DAYS: "7"
  RABBITMQ_URI: amqp://localhost
  RABBITMQ_EXCHANGE_NAME: evolution
  RABBITMQ_EVENTS_APPLICATION_STARTUP: "false"
  RABBITMQ_EVENTS_INSTANCE_CREATE: "false"
  RABBITMQ_EVENTS_INSTANCE_DELETE: "false"
  RABBITMQ_EVENTS_QRCODE_UPDATED: "false"
  RABBITMQ_EVENTS_MESSAGES_SET: "false"
  RABBITMQ_EVENTS_MESSAGES_UPSERT: "false"
  RABBITMQ_EVENTS_MESSAGES_EDITED: "false"
  RABBITMQ_EVENTS_MESSAGES_UPDATE: "false"
  RABBITMQ_EVENTS_MESSAGES_DELETE: "false"
  RABBITMQ_EVENTS_SEND_MESSAGE: "false"
  RABBITMQ_EVENTS_CONTACTS_SET: "false"
  RABBITMQ_EVENTS_CONTACTS_UPSERT: "false"
  RABBITMQ_EVENTS_CONTACTS_UPDATE: "false"
  RABBITMQ_EVENTS_PRESENCE_UPDATE: "false"
  RABBITMQ_EVENTS_CHATS_SET: "false"
  RABBITMQ_EVENTS_CHATS_UPSERT: "false"
  RABBITMQ_EVENTS_CHATS_UPDATE: "false"
  RABBITMQ_EVENTS_CHATS_DELETE: "false"
  RABBITMQ_EVENTS_GROUPS_UPSERT: "false"
  RABBITMQ_EVENTS_GROUP_UPDATE: "false"
  RABBITMQ_EVENTS_GROUP_PARTICIPANTS_UPDATE: "false"
  RABBITMQ_EVENTS_CONNECTION_UPDATE: "false"
  RABBITMQ_EVENTS_REMOVE_INSTANCE: "false"
  RABBITMQ_EVENTS_LOGOUT_INSTANCE: "false"
  RABBITMQ_EVENTS_CALL: "false"
  RABBITMQ_EVENTS_TYPEBOT_START: "false"
  RABBITMQ_EVENTS_TYPEBOT_CHANGE_STATUS: "false"
  AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES: "true"
  CACHE_REDIS_ENABLED: "false"
  CACHE_REDIS_URI: redis://{{ include "evolution-api.fullname" . }}-redis:6379/6
  CACHE_REDIS_TTL: "604800"
  CACHE_REDIS_PREFIX_KEY: evolution
  CACHE_REDIS_SAVE_INSTANCES: "false"
  CACHE_LOCAL_ENABLED: "false"