apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux.yaml
  - namespace.yaml
  - postgresql.yaml
  - deployment.yaml
  - pvc.yaml
  - configmap.yaml
  - secret.yaml
  - service.yaml