apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/hostname: n8n-webhooks.jdani.eu
    external-dns.alpha.kubernetes.io/cloudflare-proxied: false
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
  name: n8n-webhooks
  namespace: n8n
spec:
  ingressClassName: nginx
  rules:
  - host: n8n-webhooks.jdani.eu
    http:
      paths:
      - backend:
          service:
            name: n8n
            port:
              number: 8080
        path: /webhook
        pathType: Prefix
  tls:
  - hosts:
    - n8n-webhooks.jdani.eu
    secretName: n8n-webhooks-https-cert
