apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prometheus-basic-auth
  namespace: prometheus
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: basic-auth
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        auth: "{{ .pw }}"
  data:
    - secretKey: pw
      remoteRef:
        key: prometheus-ui
        version: CURRENT
        decodingStrategy: None
